
const express=require('express');
const fs=require('fs');
const path=require('path');
const multer=require('multer');
const cookieParser=require('cookie-parser');
const app=express();
const upload=multer({dest:path.join(__dirname,'uploads')});
const DATA=path.join(__dirname,'data/content.json');
const ADMIN_USER=process.env.ADMIN_USER||'admin';
const ADMIN_PASS=process.env.ADMIN_PASS||'change-this-password';
app.use(express.json());app.use(cookieParser());app.use(express.static(path.join(__dirname,'../public')));
const read=()=>JSON.parse(fs.readFileSync(DATA,'utf8')); const write=(d)=>fs.writeFileSync(DATA,JSON.stringify(d,null,2));
const auth=(req,res,next)=>req.cookies.auth==='ok'?next():res.status(401).json({error:'Unauthorized'});
app.post('/api/login',(req,res)=>{if(req.body.user===ADMIN_USER&&req.body.pass===ADMIN_PASS){res.cookie('auth','ok',{httpOnly:true,sameSite:'lax'});return res.json({ok:true});}res.status(401).json({error:'Invalid'});});
app.get('/api/content',auth,(req,res)=>res.json(read()));
app.post('/api/content/:type',auth,(req,res)=>{const d=read(); const t=req.params.type; if(!Array.isArray(d[t])) return res.status(404).end(); d[t].push(req.body); write(d); res.json({ok:true});});
app.delete('/api/content/:type/:idx',auth,(req,res)=>{const d=read(); const t=req.params.type; d[t].splice(Number(req.params.idx),1); write(d); res.json({ok:true});});
app.post('/api/bookings',upload.single('image'),(req,res)=>{const d=read();d.bookings.push({...req.body,image:req.file?.filename||null,createdAt:new Date().toISOString()});write(d);res.json({ok:true,whatsapp:`https://wa.me/6583122991?text=Booking%20received%20for%20${encodeURIComponent(req.body.service||'service')}`});});
app.listen(process.env.PORT||8787,()=>console.log('Server running'));
